[package]
name = "checkpoint"
version.workspace = true
edition.workspace = true
description = "Checkpointing and store abstractions: traits, data types, default in-memory implementations"
license.workspace = true
authors.workspace = true

[dependencies]
async-trait = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
