module.exports = {
  apps: [
    {
      name: 'loom-server',
      script: 'C:\\Users\\heycj\\dev\\worktrees\\loom\\cli-server-backend\\scripts\\pm2\\run-loom.cjs',
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 20,
      max_memory_restart: '4G',
      kill_timeout: 8000,
      out_file: 'C:\\Users\\heycj\\dev\\worktrees\\loom\\cli-server-backend\\logs\\pm2\\loom-out.log',
      error_file: 'C:\\Users\\heycj\\dev\\worktrees\\loom\\cli-server-backend\\logs\\pm2\\loom-error.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'openchamber-api',
      script: 'C:\\Users\\heycj\\dev\\worktrees\\loom\\cli-server-backend\\scripts\\pm2\\run-openchamber-api.cjs',
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 20,
      max_memory_restart: '2G',
      kill_timeout: 5000,
      out_file: 'C:\\Users\\heycj\\dev\\worktrees\\loom\\cli-server-backend\\logs\\pm2\\openchamber-api-out.log',
      error_file: 'C:\\Users\\heycj\\dev\\worktrees\\loom\\cli-server-backend\\logs\\pm2\\openchamber-api-error.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'openchamber-web',
      script: 'C:\\Users\\heycj\\dev\\worktrees\\loom\\cli-server-backend\\scripts\\pm2\\run-openchamber-web.cjs',
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      kill_timeout: 5000,
      out_file: 'C:\\Users\\heycj\\dev\\worktrees\\loom\\cli-server-backend\\logs\\pm2\\openchamber-web-out.log',
      error_file: 'C:\\Users\\heycj\\dev\\worktrees\\loom\\cli-server-backend\\logs\\pm2\\openchamber-web-error.log',
      merge_logs: true,
      time: true,
    },
  ],
};