module.exports = {
  apps: [
    {
      name: 'anureo-server',
      script: 'C:\\Users\\heycj\\dev\\worktrees\\anureo\\cli-server-backend\\scripts\\pm2\\run-anureo.cjs',
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 20,
      max_memory_restart: '4G',
      kill_timeout: 8000,
      out_file: 'C:\\Users\\heycj\\dev\\worktrees\\anureo\\cli-server-backend\\logs\\pm2\\anureo-out.log',
      error_file: 'C:\\Users\\heycj\\dev\\worktrees\\anureo\\cli-server-backend\\logs\\pm2\\anureo-error.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'anureo-api',
      script: 'C:\\Users\\heycj\\dev\\worktrees\\anureo\\cli-server-backend\\scripts\\pm2\\run-anureo-api.cjs',
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 20,
      max_memory_restart: '2G',
      kill_timeout: 5000,
      out_file: 'C:\\Users\\heycj\\dev\\worktrees\\anureo\\cli-server-backend\\logs\\pm2\\anureo-api-out.log',
      error_file: 'C:\\Users\\heycj\\dev\\worktrees\\anureo\\cli-server-backend\\logs\\pm2\\anureo-api-error.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'anureo-web',
      script: 'C:\\Users\\heycj\\dev\\worktrees\\anureo\\cli-server-backend\\scripts\\pm2\\run-anureo-web.cjs',
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      kill_timeout: 5000,
      out_file: 'C:\\Users\\heycj\\dev\\worktrees\\anureo\\cli-server-backend\\logs\\pm2\\anureo-web-out.log',
      error_file: 'C:\\Users\\heycj\\dev\\worktrees\\anureo\\cli-server-backend\\logs\\pm2\\anureo-web-error.log',
      merge_logs: true,
      time: true,
    },
  ],
};