//! Conversation history cell rendering.
//!
//! Renders individual conversation turns — user messages, assistant replies,
//! tool calls, and system messages — as ratatui widgets.
//!
//! Each variant of [`HistoryCell`] implements [`Renderable`] with a distinct
//! visual style:
//!
//! | Variant             | Style                    |
//! |---------------------|--------------------------|
//! | `UserMessage`       | Cyan border, " User "    |
//! | `AssistantMessage`  | Green border, " Assistant " |
//! | `ToolCall`          | Yellow, single-line      |
//! | `SystemMessage`     | Italic, colour by style  |
//!
//! # Integration
//!
//! ```ignore
//! let cell = HistoryCell::user_message("Hello".into());
//! cell.render(area, buf);
//! ```

use crate::tui::render::Renderable;
use chrono_humanize::{Accuracy, HumanTime, Tense};
use ratatui::{
    buffer::Buffer,
    layout::Rect,
    prelude::Widget,
    style::{Color, Modifier, Style},
    text::{Line, Span},
    widgets::{Block, Borders, Paragraph, Wrap},
};
use serde_json::Value;

// ---------------------------------------------------------------------------
// ToolStatus
// ---------------------------------------------------------------------------

/// Execution status of a tool call.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ToolStatus {
    /// The tool is currently running.
    Running,
    /// The tool completed successfully.
    Completed,
    /// The tool failed with an error.
    Failed,
    /// The tool is queued and waiting to execute.
    Pending,
}

// ---------------------------------------------------------------------------
// SystemMessageStyle
// ---------------------------------------------------------------------------

/// Semantic style for a system message.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SystemMessageStyle {
    /// Informational message (blue).
    Info,
    /// Warning message (yellow).
    Warning,
    /// Error message (red).
    Error,
}

// ---------------------------------------------------------------------------
// HistoryCell
// ---------------------------------------------------------------------------

/// A single completed conversation turn.
///
/// Each variant represents a different kind of message in the conversation
/// history and renders with a distinct visual style.
#[derive(Debug, Clone)]
pub enum HistoryCell {
    /// A message sent by the user.
    UserMessage {
        content: String,
        timestamp: chrono::DateTime<chrono::Utc>,
    },
    /// A reply generated by the assistant.
    AssistantMessage {
        content: String,
        timestamp: chrono::DateTime<chrono::Utc>,
    },
    /// A tool invocation made by the assistant.
    ToolCall {
        tool_name: String,
        args: Value,
        result: Option<String>,
        status: ToolStatus,
        timestamp: chrono::DateTime<chrono::Utc>,
    },
    /// A system-level message (info, warning, error).
    SystemMessage {
        content: String,
        style: SystemMessageStyle,
    },
}

// ---------------------------------------------------------------------------
// Constructors
// ---------------------------------------------------------------------------

impl HistoryCell {
    /// Create a new user message cell.
    pub fn user_message(content: String) -> Self {
        Self::UserMessage {
            content,
            timestamp: chrono::Utc::now(),
        }
    }

    /// Create a new assistant message cell.
    pub fn assistant_message(content: String) -> Self {
        Self::AssistantMessage {
            content,
            timestamp: chrono::Utc::now(),
        }
    }

    /// Create a new tool call cell.
    pub fn tool_call(
        tool_name: String,
        args: Value,
        result: Option<String>,
        status: ToolStatus,
    ) -> Self {
        Self::ToolCall {
            tool_name,
            args,
            result,
            status,
            timestamp: chrono::Utc::now(),
        }
    }

    /// Create a new system message cell.
    pub fn system_message(content: String, style: SystemMessageStyle) -> Self {
        Self::SystemMessage { content, style }
    }

    /// Return a human-readable relative timestamp.
    fn format_timestamp(ts: &chrono::DateTime<chrono::Utc>) -> String {
        let now = chrono::Utc::now();
        let delta = now.signed_duration_since(*ts);
        HumanTime::from(delta).to_text_en(Accuracy::Rough, Tense::Past)
    }
}

// ---------------------------------------------------------------------------
// Renderable impl
// ---------------------------------------------------------------------------

impl Renderable for HistoryCell {
    fn render(&self, area: Rect, buf: &mut Buffer) {
        match self {
            Self::UserMessage { content, timestamp } => {
                let time_str = Self::format_timestamp(timestamp);
                let title = format!(" User {} ", time_str);

                let block = Block::default()
                    .title(title)
                    .borders(Borders::ALL)
                    .border_style(Style::default().fg(Color::Cyan));

                let paragraph = Paragraph::new(content.as_str())
                    .block(block)
                    .wrap(Wrap { trim: false });
                paragraph.render(area, buf);
            }
            Self::AssistantMessage { content, timestamp } => {
                let time_str = Self::format_timestamp(timestamp);
                let title = format!(" Assistant {} ", time_str);

                let block = Block::default()
                    .title(title)
                    .borders(Borders::ALL)
                    .border_style(Style::default().fg(Color::Green));

                let paragraph = Paragraph::new(content.as_str())
                    .block(block)
                    .wrap(Wrap { trim: false });
                paragraph.render(area, buf);
            }
            Self::ToolCall {
                tool_name,
                args,
                result,
                status,
                ..
            } => {
                let status_symbol = match status {
                    ToolStatus::Running => "◌",
                    ToolStatus::Completed => "✓",
                    ToolStatus::Failed => "✗",
                    ToolStatus::Pending => "○",
                };
                let status_label = match status {
                    ToolStatus::Running => "运行中",
                    ToolStatus::Completed => "已完成",
                    ToolStatus::Failed => "失败",
                    ToolStatus::Pending => "等待中",
                };

                // Build a multi-line tool call display.
                let mut lines: Vec<Line> = Vec::new();

                // Line 1: status line
                let status_style = match status {
                    ToolStatus::Running => Style::default().fg(Color::Cyan),
                    ToolStatus::Completed => Style::default().fg(Color::Green),
                    ToolStatus::Failed => Style::default().fg(Color::Red),
                    ToolStatus::Pending => Style::default().fg(Color::DarkGray),
                };
                let status_text = format!(
                    " {} {} {} ",
                    status_symbol, tool_name, status_label
                );
                lines.push(Line::from(Span::styled(status_text, status_style)));

                // Line 2: args (collapsed to a single line)
                let args_str = if args.is_object() {
                    let keys: Vec<&str> = args
                        .as_object()
                        .map(|obj| obj.keys().map(|k| k.as_str()).collect())
                        .unwrap_or_default();
                    format!("args: {}", keys.join(", "))
                } else {
                    let raw = args.to_string();
                    if raw.len() > 80 {
                        format!("args: {}…", &raw[..77])
                    } else {
                        format!("args: {}", raw)
                    }
                };
                lines.push(Line::from(Span::styled(
                    args_str,
                    Style::default().fg(Color::DarkGray),
                )));

                // Line 3: result (if present)
                if let Some(res) = result {
                    if !res.is_empty() {
                        let preview = if res.len() > 120 {
                            // Safe truncation: use char boundary, not byte boundary
                            let truncated: String = res.chars().take(117).collect();
                            format!("{}…", truncated)
                        } else {
                            res.clone()
                        };
                        lines.push(Line::from(Span::styled(
                            preview,
                            Style::default().fg(Color::DarkGray),
                        )));
                    }
                }

                let paragraph = Paragraph::new(lines).wrap(Wrap { trim: false });
                paragraph.render(area, buf);
            }
            Self::SystemMessage { content, style } => {
                let color = match style {
                    SystemMessageStyle::Info => Color::Blue,
                    SystemMessageStyle::Warning => Color::Yellow,
                    SystemMessageStyle::Error => Color::Red,
                };

                let paragraph = Paragraph::new(content.as_str())
                    .style(Style::default().fg(color).add_modifier(Modifier::ITALIC))
                    .wrap(Wrap { trim: false });
                paragraph.render(area, buf);
            }
        }
    }

    fn desired_height(&self, width: u16) -> u16 {
        match self {
            Self::UserMessage { content, .. } | Self::AssistantMessage { content, .. } => {
                if width == 0 {
                    return content.lines().count() as u16 + 2;
                }
                // Estimate wrapped line count: for each line, compute how many
                // terminal rows it occupies given the available width.
                let border_width = 2u16; // left + right border
                let inner_width = width.saturating_sub(border_width).max(1);
                let total_rows: u16 = content
                    .lines()
                    .map(|line| {
                        let len = unicode_width::UnicodeWidthStr::width(line) as u16;
                        // Each line occupies at least 1 row, plus potential wraps.
                        len.div_ceil(inner_width).max(1)
                    })
                    .sum();
                // +2 for top/bottom borders
                total_rows.saturating_add(2)
            }
            Self::ToolCall { result, .. } => {
                let mut h = 2u16; // status line + args line
                if result.as_ref().is_some_and(|r| !r.is_empty()) {
                    h += 1;
                }
                h
            }
            Self::SystemMessage { content, .. } => {
                content.lines().count() as u16
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crossterm::cursor::SetCursorStyle;
    use ratatui::buffer::Buffer;
    use ratatui::layout::Rect;

    // -- ToolStatus ---------------------------------------------------------

    #[test]
    fn test_tool_status_debug_clone_copy() {
        let s = ToolStatus::Running;
        let copied = s;
        assert_eq!(format!("{:?}", s), "Running");
        assert_eq!(copied, s);
    }

    #[test]
    fn test_tool_status_all_variants_distinct() {
        let variants = [
            ToolStatus::Running,
            ToolStatus::Completed,
            ToolStatus::Failed,
            ToolStatus::Pending,
        ];
        for i in 0..variants.len() {
            for j in (i + 1)..variants.len() {
                assert_ne!(variants[i], variants[j]);
            }
        }
    }

    // -- SystemMessageStyle ------------------------------------------------

    #[test]
    fn test_system_message_style_debug_clone_copy() {
        let s = SystemMessageStyle::Info;
        let copied = s;
        assert_eq!(format!("{:?}", s), "Info");
        assert_eq!(copied, s);
    }

    // -- HistoryCell constructors ------------------------------------------

    #[test]
    fn test_user_message_constructor() {
        let cell = HistoryCell::user_message("hello".to_string());
        match cell {
            HistoryCell::UserMessage { content, .. } => {
                assert_eq!(content, "hello");
            }
            _ => panic!("expected UserMessage"),
        }
    }

    #[test]
    fn test_assistant_message_constructor() {
        let cell = HistoryCell::assistant_message("world".to_string());
        match cell {
            HistoryCell::AssistantMessage { content, .. } => {
                assert_eq!(content, "world");
            }
            _ => panic!("expected AssistantMessage"),
        }
    }

    #[test]
    fn test_tool_call_constructor() {
        let args = serde_json::json!({"cmd": "ls"});
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            args.clone(),
            Some("ok".to_string()),
            ToolStatus::Completed,
        );
        match cell {
            HistoryCell::ToolCall {
                tool_name,
                args: a,
                result,
                status,
                ..
            } => {
                assert_eq!(tool_name, "bash");
                assert_eq!(a, args);
                assert_eq!(result, Some("ok".to_string()));
                assert_eq!(status, ToolStatus::Completed);
            }
            _ => panic!("expected ToolCall"),
        }
    }

    #[test]
    fn test_system_message_constructor() {
        let cell =
            HistoryCell::system_message("done".to_string(), SystemMessageStyle::Info);
        match cell {
            HistoryCell::SystemMessage { content, style } => {
                assert_eq!(content, "done");
                assert_eq!(style, SystemMessageStyle::Info);
            }
            _ => panic!("expected SystemMessage"),
        }
    }

    // -- Renderable trait defaults -----------------------------------------

    #[test]
    fn test_history_cell_cursor_pos_default() {
        let cell = HistoryCell::user_message("hi".to_string());
        let area = Rect::new(0, 0, 80, 5);
        assert_eq!(cell.cursor_pos(area), None);
    }

    #[test]
    fn test_history_cell_cursor_style_default() {
        let cell = HistoryCell::user_message("hi".to_string());
        let area = Rect::new(0, 0, 80, 5);
        assert_eq!(cell.cursor_style(area), SetCursorStyle::DefaultUserShape);
    }

    // -- desired_height ----------------------------------------------------

    #[test]
    fn test_desired_height_user_message_single_line() {
        let cell = HistoryCell::user_message("hello".to_string());
        let h = cell.desired_height(80);
        // 1 line + 2 borders = 3
        assert_eq!(h, 3);
    }

    #[test]
    fn test_desired_height_user_message_multi_line() {
        let cell = HistoryCell::user_message("hello\nworld".to_string());
        let h = cell.desired_height(80);
        // 2 lines + 2 borders = 4
        assert_eq!(h, 4);
    }

    #[test]
    fn test_desired_height_user_message_zero_width() {
        let cell = HistoryCell::user_message("hello".to_string());
        let h = cell.desired_height(0);
        // No crash; 1 line + 2 borders = 3
        assert_eq!(h, 3);
    }

    #[test]
    fn test_desired_height_assistant_message() {
        let cell = HistoryCell::assistant_message("a\nb\nc".to_string());
        let h = cell.desired_height(80);
        // 3 lines + 2 borders = 5
        assert_eq!(h, 5);
    }

    #[test]
    fn test_desired_height_tool_call_no_result() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            None,
            ToolStatus::Running,
        );
        let h = cell.desired_height(80);
        // 2 lines (status + args)
        assert_eq!(h, 2);
    }

    #[test]
    fn test_desired_height_tool_call_with_result() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            Some("file1\nfile2".to_string()),
            ToolStatus::Completed,
        );
        let h = cell.desired_height(80);
        // 3 lines (status + args + result)
        assert_eq!(h, 3);
    }

    #[test]
    fn test_desired_height_tool_call_empty_result() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            Some(String::new()),
            ToolStatus::Completed,
        );
        let h = cell.desired_height(80);
        // Empty result should not add a line
        assert_eq!(h, 2);
    }

    #[test]
    fn test_desired_height_system_message() {
        let cell =
            HistoryCell::system_message("info".to_string(), SystemMessageStyle::Info);
        assert_eq!(cell.desired_height(80), 1);
    }

    #[test]
    fn test_desired_height_system_message_multi_line() {
        let cell = HistoryCell::system_message(
            "line1\nline2\nline3".to_string(),
            SystemMessageStyle::Warning,
        );
        assert_eq!(cell.desired_height(80), 3);
    }

    // -- Render smoke tests ------------------------------------------------

    #[test]
    fn test_render_user_message_no_panic() {
        let cell = HistoryCell::user_message("hello".to_string());
        let area = Rect::new(0, 0, 80, 3);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);
    }

    #[test]
    fn test_render_assistant_message_no_panic() {
        let cell = HistoryCell::assistant_message("reply".to_string());
        let area = Rect::new(0, 0, 80, 3);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);
    }

    #[test]
    fn test_render_tool_call_running() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            None,
            ToolStatus::Running,
        );
        let area = Rect::new(0, 0, 80, 2);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);
        // First cell should show the spinner symbol
        let cell0 = buf.cell((0, 0)).expect("cell (0,0)");
        assert_eq!(cell0.symbol(), " ");
    }

    #[test]
    fn test_render_tool_call_completed() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            Some("ok".to_string()),
            ToolStatus::Completed,
        );
        let area = Rect::new(0, 0, 80, 3);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);
    }

    #[test]
    fn test_render_tool_call_failed() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            Some("error: not found".to_string()),
            ToolStatus::Failed,
        );
        let area = Rect::new(0, 0, 80, 3);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);
    }

    #[test]
    fn test_render_system_message_info() {
        let cell =
            HistoryCell::system_message("info msg".to_string(), SystemMessageStyle::Info);
        let area = Rect::new(0, 0, 80, 1);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);
    }

    #[test]
    fn test_render_system_message_warning() {
        let cell = HistoryCell::system_message(
            "warning msg".to_string(),
            SystemMessageStyle::Warning,
        );
        let area = Rect::new(0, 0, 80, 1);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);
    }

    #[test]
    fn test_render_system_message_error() {
        let cell = HistoryCell::system_message(
            "error msg".to_string(),
            SystemMessageStyle::Error,
        );
        let area = Rect::new(0, 0, 80, 1);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);
    }

    // -- Boundary conditions -----------------------------------------------

    #[test]
    fn test_render_empty_user_message() {
        let cell = HistoryCell::user_message(String::new());
        let area = Rect::new(0, 0, 80, 2);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);
        assert_eq!(cell.desired_height(80), 2);
    }

    #[test]
    fn test_render_empty_assistant_message() {
        let cell = HistoryCell::assistant_message(String::new());
        let area = Rect::new(0, 0, 80, 2);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);
    }

    #[test]
    fn test_render_zero_width_area() {
        let cell = HistoryCell::user_message("hello".to_string());
        let area = Rect::new(0, 0, 0, 3);
        let mut buf = Buffer::empty(Rect::new(0, 0, 80, 5));
        cell.render(area, &mut buf); // No panic
    }

    #[test]
    fn test_render_zero_height_area() {
        let cell = HistoryCell::user_message("hello".to_string());
        let area = Rect::new(0, 0, 80, 0);
        let mut buf = Buffer::empty(Rect::new(0, 0, 80, 5));
        cell.render(area, &mut buf); // No panic
    }

    #[test]
    fn test_render_very_long_content() {
        let long = "a".repeat(10_000);
        let cell = HistoryCell::user_message(long);
        let area = Rect::new(0, 0, 80, 10);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf); // No panic, no crash
    }

    #[test]
    fn test_render_all_variants_no_panic() {
        let cells: Vec<HistoryCell> = vec![
            HistoryCell::user_message("hi".to_string()),
            HistoryCell::assistant_message("hello".to_string()),
            HistoryCell::tool_call(
                "bash".to_string(),
                serde_json::json!({"cmd": "ls"}),
                None,
                ToolStatus::Running,
            ),
            HistoryCell::tool_call(
                "bash".to_string(),
                serde_json::json!({"cmd": "ls"}),
                Some("ok".to_string()),
                ToolStatus::Completed,
            ),
            HistoryCell::tool_call(
                "bash".to_string(),
                serde_json::json!({"cmd": "ls"}),
                Some("fail".to_string()),
                ToolStatus::Failed,
            ),
            HistoryCell::system_message("info".to_string(), SystemMessageStyle::Info),
            HistoryCell::system_message("warn".to_string(), SystemMessageStyle::Warning),
            HistoryCell::system_message("err".to_string(), SystemMessageStyle::Error),
        ];

        let area = Rect::new(0, 0, 80, 10);
        let mut buf = Buffer::empty(area);
        for cell in &cells {
            cell.render(area, &mut buf);
        }
    }

    // =========================================================================
    // desired_height: wrapping & edge cases
    // =========================================================================

    #[test]
    fn test_desired_height_user_message_narrow_width_wraps() {
        let cell = HistoryCell::user_message("hello world this is a long line".to_string());
        // Very narrow width -> content wraps
        let h_wide = cell.desired_height(80);
        let h_narrow = cell.desired_height(5);
        // Narrow width should require more rows
        assert!(h_narrow >= h_wide, "narrow width should need >= rows than wide width");
    }

    #[test]
    fn test_desired_height_user_message_zero_width_edge() {
        let cell = HistoryCell::user_message("hello\nworld".to_string());
        let h = cell.desired_height(0);
        // width=0 is handled specially: returns content.lines() + 2
        // "hello\nworld" = 2 lines + 2 borders = 4
        assert_eq!(h, 4);
    }

    #[test]
    fn test_desired_height_user_message_with_cjk() {
        // CJK characters have unicode width 2
        let cell = HistoryCell::user_message("你好世界".to_string());
        // At width=80 (inner_width=78), 4 chars * 2 width = 8, fits in 1 row
        let h = cell.desired_height(80);
        assert_eq!(h, 3); // 1 row + 2 borders
    }

    #[test]
    fn test_desired_height_user_message_cjk_wraps_at_narrow_width() {
        // CJK chars that need wrapping
        let cell = HistoryCell::user_message("你好世界".to_string());
        // inner_width=1 (width=3, border=2): each CJK char is width 2, so each needs 2 rows
        // 4 chars * 2 rows = 8 rows + 2 borders = 10
        let h = cell.desired_height(3);
        assert_eq!(h, 10);
    }

    #[test]
    fn test_desired_height_user_message_exact_fit() {
        // Content exactly fits the inner width
        let cell = HistoryCell::user_message("12345678".to_string());
        let h = cell.desired_height(10); // inner_width = 8, 1 row
        assert_eq!(h, 3); // 1 row + 2 borders
    }

    #[test]
    fn test_desired_height_user_message_wraps_exactly() {
        // Content wraps at exactly the right boundary
        let cell = HistoryCell::user_message("123456789".to_string());
        let h = cell.desired_height(10); // inner_width = 8, 9 chars -> 2 rows
        assert_eq!(h, 4); // 2 rows + 2 borders
    }

    #[test]
    fn test_desired_height_user_message_width_one() {
        // width=1, inner_width = 1.max(1) = 1
        let cell = HistoryCell::user_message("abc".to_string());
        let h = cell.desired_height(1); // inner_width = 1, 3 chars -> 3 rows + 2 borders = 5
        assert_eq!(h, 5);
    }

    #[test]
    fn test_desired_height_system_message_empty() {
        let cell = HistoryCell::system_message(String::new(), SystemMessageStyle::Info);
        // Empty string has 0 lines
        assert_eq!(cell.desired_height(80), 0);
    }

    #[test]
    fn test_desired_height_tool_call_non_object_args_string() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::Value::String("ls -la".to_string()),
            None,
            ToolStatus::Running,
        );
        // Non-object args: status line + args line = 2
        assert_eq!(cell.desired_height(80), 2);
    }

    #[test]
    fn test_desired_height_tool_call_non_object_args_number() {
        let cell = HistoryCell::tool_call(
            "calc".to_string(),
            serde_json::json!(42),
            None,
            ToolStatus::Completed,
        );
        assert_eq!(cell.desired_height(80), 2);
    }

    #[test]
    fn test_desired_height_tool_call_non_object_args_array() {
        let cell = HistoryCell::tool_call(
            "list".to_string(),
            serde_json::json!(["a", "b", "c"]),
            None,
            ToolStatus::Completed,
        );
        assert_eq!(cell.desired_height(80), 2);
    }

    #[test]
    fn test_desired_height_tool_call_non_object_args_null() {
        let cell = HistoryCell::tool_call(
            "test".to_string(),
            serde_json::Value::Null,
            None,
            ToolStatus::Pending,
        );
        assert_eq!(cell.desired_height(80), 2);
    }

    #[test]
    fn test_desired_height_tool_call_empty_object_args() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({}),
            None,
            ToolStatus::Running,
        );
        assert_eq!(cell.desired_height(80), 2);
    }

    #[test]
    fn test_desired_height_tool_call_pending_status() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            None,
            ToolStatus::Pending,
        );
        assert_eq!(cell.desired_height(80), 2);
    }

    #[test]
    fn test_desired_height_tool_call_very_long_args_truncated() {
        // Args longer than 80 chars get truncated: "args: xxx…" — still 1 line
        let long_key = "a".repeat(100);
        let args = serde_json::json!({&long_key: "value"});
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            args,
            None,
            ToolStatus::Running,
        );
        assert_eq!(cell.desired_height(80), 2);
    }

    #[test]
    fn test_desired_height_tool_call_with_result_no_result_line_for_empty() {
        // Empty string result should not add a line
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            Some(String::new()),
            ToolStatus::Completed,
        );
        assert_eq!(cell.desired_height(80), 2);
    }

    #[test]
    fn test_desired_height_tool_call_very_long_result() {
        let long_result = "x".repeat(200);
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            Some(long_result),
            ToolStatus::Completed,
        );
        // Long result still counts as 1 line
        assert_eq!(cell.desired_height(80), 3);
    }

    #[test]
    fn test_desired_height_user_message_max_width() {
        let cell = HistoryCell::user_message("hello".to_string());
        // u16::MAX should not panic or overflow
        let h = cell.desired_height(u16::MAX);
        assert_eq!(h, 3); // 1 row + 2 borders
    }

    #[test]
    fn test_desired_height_user_message_multiline_narrow() {
        let cell = HistoryCell::user_message("hello\nworld".to_string());
        // width=2: inner_width=1, each line=5 chars -> 5 rows per line = 10 + 2 = 12
        let h = cell.desired_height(2);
        assert_eq!(h, 12);
    }

    // =========================================================================
    // Render content verification
    // =========================================================================

    #[test]
    fn test_render_user_message_contains_content() {
        let cell = HistoryCell::user_message("Hello, World!".to_string());
        let area = Rect::new(0, 0, 80, 5);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);

        // The content should appear somewhere in the buffer (inside the bordered area)
        // symbol() returns a single character, so check for the first char "H"
        let content_found = (0..area.height).any(|y| {
            (0..area.width).any(|x| {
                buf.cell((x, y))
                    .map(|c| c.symbol() == "H")
                    .unwrap_or(false)
            })
        });
        assert!(content_found, "UserMessage content should be rendered in the buffer");
    }

    #[test]
    fn test_render_assistant_message_contains_content() {
        let cell = HistoryCell::assistant_message("Assistant reply".to_string());
        let area = Rect::new(0, 0, 80, 5);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);

        let content_found = (0..area.height).any(|y| {
            (0..area.width).any(|x| {
                buf.cell((x, y))
                    .map(|c| c.symbol() == "A")
                    .unwrap_or(false)
            })
        });
        assert!(content_found, "AssistantMessage content should be rendered in the buffer");
    }

    #[test]
    fn test_render_tool_call_running_symbol() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            None,
            ToolStatus::Running,
        );
        let area = Rect::new(0, 0, 80, 2);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);

        // The "◌" symbol should be in the buffer
        let symbol_found = (0..area.height).any(|y| {
            (0..area.width).any(|x| {
                buf.cell((x, y))
                    .map(|c| c.symbol().contains("◌"))
                    .unwrap_or(false)
            })
        });
        assert!(symbol_found, "Running tool call should show ◌ symbol");
    }

    #[test]
    fn test_render_tool_call_completed_symbol() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            None,
            ToolStatus::Completed,
        );
        let area = Rect::new(0, 0, 80, 2);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);

        let symbol_found = (0..area.height).any(|y| {
            (0..area.width).any(|x| {
                buf.cell((x, y))
                    .map(|c| c.symbol().contains("✓"))
                    .unwrap_or(false)
            })
        });
        assert!(symbol_found, "Completed tool call should show ✓ symbol");
    }

    #[test]
    fn test_render_tool_call_failed_symbol() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            None,
            ToolStatus::Failed,
        );
        let area = Rect::new(0, 0, 80, 2);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);

        let symbol_found = (0..area.height).any(|y| {
            (0..area.width).any(|x| {
                buf.cell((x, y))
                    .map(|c| c.symbol().contains("✗"))
                    .unwrap_or(false)
            })
        });
        assert!(symbol_found, "Failed tool call should show ✗ symbol");
    }

    #[test]
    fn test_render_tool_call_pending_symbol() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            None,
            ToolStatus::Pending,
        );
        let area = Rect::new(0, 0, 80, 2);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);

        let symbol_found = (0..area.height).any(|y| {
            (0..area.width).any(|x| {
                buf.cell((x, y))
                    .map(|c| c.symbol().contains("○"))
                    .unwrap_or(false)
            })
        });
        assert!(symbol_found, "Pending tool call should show ○ symbol");
    }

    #[test]
    fn test_render_tool_call_shows_tool_name() {
        let cell = HistoryCell::tool_call(
            "my_tool".to_string(),
            serde_json::json!({"cmd": "ls"}),
            None,
            ToolStatus::Running,
        );
        let area = Rect::new(0, 0, 80, 2);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);

        let name_found = (0..area.height).any(|y| {
            (0..area.width).any(|x| {
                buf.cell((x, y))
                    .map(|c| c.symbol() == "m" || c.symbol() == "y")
                    .unwrap_or(false)
            })
        });
        assert!(name_found, "Tool call should show tool name");
    }

    #[test]
    fn test_render_tool_call_shows_args_keys() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls", "path": "/tmp"}),
            None,
            ToolStatus::Running,
        );
        let area = Rect::new(0, 0, 80, 3);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);

        // The args line should contain "args: cmd, path"
        let args_found = (0..area.height).any(|y| {
            (0..area.width).any(|x| {
                buf.cell((x, y))
                    .map(|c| c.symbol() == "c" || c.symbol() == "p")
                    .unwrap_or(false)
            })
        });
        assert!(args_found, "Tool call should show arg keys");
    }

    #[test]
    fn test_render_tool_call_with_result_shows_preview() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            Some("result output".to_string()),
            ToolStatus::Completed,
        );
        let area = Rect::new(0, 0, 80, 3);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);

        let result_found = (0..area.height).any(|y| {
            (0..area.width).any(|x| {
                buf.cell((x, y))
                    .map(|c| c.symbol() == "r")
                    .unwrap_or(false)
            })
        });
        assert!(result_found, "Tool call should show result content");
    }

    #[test]
    fn test_render_tool_call_result_truncated_at_120() {
        let long_result = "x".repeat(150);
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            Some(long_result.clone()),
            ToolStatus::Completed,
        );
        let area = Rect::new(0, 0, 200, 3);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);

        // The result should be truncated: first 117 chars + "…"
        // The "…" is at position 117, so use a buffer wide enough to contain it
        let trunc_found = (0..area.height).any(|y| {
            (0..200.min(area.width)).any(|x| {
                buf.cell((x, y))
                    .map(|c| c.symbol() == "…")
                    .unwrap_or(false)
            })
        });
        assert!(trunc_found, "Truncated result should contain ellipsis");
    }

    #[test]
    fn test_render_tool_call_args_truncated_at_80() {
        // Args with long key triggers truncation — verify args content is rendered
        let long_key = "a".repeat(100);
        let args = serde_json::json!({&long_key: "value"});
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            args,
            None,
            ToolStatus::Running,
        );
        let area = Rect::new(0, 0, 200, 2);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);

        // The args line should contain "args:" prefix
        let args_found = (0..area.height).any(|y| {
            (0..area.width).any(|x| {
                buf.cell((x, y))
                    .map(|c| c.symbol() == "a" || c.symbol() == "g")
                    .unwrap_or(false)
            })
        });
        assert!(args_found, "Args content should be rendered in buffer");
    }

    #[test]
    fn test_render_system_message_info_has_italic() {
        let cell = HistoryCell::system_message("info text".to_string(), SystemMessageStyle::Info);
        let area = Rect::new(0, 0, 80, 1);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);

        // The content should be rendered
        let content_found = (0..area.width).any(|x| {
            buf.cell((x, 0))
                .map(|c| c.symbol() == "i")
                .unwrap_or(false)
        });
        assert!(content_found, "SystemMessage info should render content");
    }

    #[test]
    fn test_render_system_message_warning_renders() {
        let cell = HistoryCell::system_message("warning text".to_string(), SystemMessageStyle::Warning);
        let area = Rect::new(0, 0, 80, 1);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);

        let content_found = (0..area.width).any(|x| {
            buf.cell((x, 0))
                .map(|c| c.symbol() == "w")
                .unwrap_or(false)
        });
        assert!(content_found, "SystemMessage warning should render content");
    }

    #[test]
    fn test_render_system_message_error_renders() {
        let cell = HistoryCell::system_message("error text".to_string(), SystemMessageStyle::Error);
        let area = Rect::new(0, 0, 80, 1);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf);

        let content_found = (0..area.width).any(|x| {
            buf.cell((x, 0))
                .map(|c| c.symbol() == "e")
                .unwrap_or(false)
        });
        assert!(content_found, "SystemMessage error should render content");
    }

    #[test]
    fn test_render_system_message_empty_content() {
        let cell = HistoryCell::system_message(String::new(), SystemMessageStyle::Info);
        let area = Rect::new(0, 0, 80, 1);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf); // No panic
    }

    #[test]
    fn test_render_system_message_multi_line() {
        let cell = HistoryCell::system_message(
            "line1\nline2\nline3".to_string(),
            SystemMessageStyle::Warning,
        );
        let area = Rect::new(0, 0, 80, 3);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf); // No panic
    }

    #[test]
    fn test_render_tool_call_non_object_args_string_renders() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::Value::String("ls -la".to_string()),
            None,
            ToolStatus::Running,
        );
        let area = Rect::new(0, 0, 80, 2);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf); // No panic
    }

    #[test]
    fn test_render_tool_call_non_object_args_number_renders() {
        let cell = HistoryCell::tool_call(
            "calc".to_string(),
            serde_json::json!(42),
            None,
            ToolStatus::Completed,
        );
        let area = Rect::new(0, 0, 80, 2);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf); // No panic
    }

    #[test]
    fn test_render_tool_call_non_object_args_array_renders() {
        let cell = HistoryCell::tool_call(
            "list".to_string(),
            serde_json::json!(["a", "b", "c"]),
            None,
            ToolStatus::Completed,
        );
        let area = Rect::new(0, 0, 80, 2);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf); // No panic
    }

    #[test]
    fn test_render_tool_call_non_object_args_null_renders() {
        let cell = HistoryCell::tool_call(
            "test".to_string(),
            serde_json::Value::Null,
            None,
            ToolStatus::Pending,
        );
        let area = Rect::new(0, 0, 80, 2);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf); // No panic
    }

    // =========================================================================
    // Error / no-panic scenarios
    // =========================================================================

    #[test]
    fn test_render_very_large_area() {
        let cell = HistoryCell::user_message("hello".to_string());
        let area = Rect::new(0, 0, 500, 200);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf); // No panic
    }

    #[test]
    fn test_render_minimal_area() {
        let cell = HistoryCell::user_message("hello".to_string());
        let area = Rect::new(0, 0, 1, 1);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf); // No panic
    }

    #[test]
    fn test_render_tool_call_minimal_area() {
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            Some("result".to_string()),
            ToolStatus::Completed,
        );
        let area = Rect::new(0, 0, 1, 1);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf); // No panic
    }

    #[test]
    fn test_render_system_message_minimal_area() {
        let cell = HistoryCell::system_message("error".to_string(), SystemMessageStyle::Error);
        let area = Rect::new(0, 0, 1, 1);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf); // No panic
    }

    #[test]
    fn test_render_very_long_single_line_content() {
        let long = "a".repeat(100_000);
        let cell = HistoryCell::user_message(long);
        let area = Rect::new(0, 0, 80, 20);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf); // No panic
    }

    #[test]
    fn test_render_very_long_multi_line_content() {
        let lines: Vec<String> = (0..10_000).map(|i| format!("line_{}", i)).collect();
        let content = lines.join("\n");
        let cell = HistoryCell::assistant_message(content);
        let area = Rect::new(0, 0, 80, 10);
        let mut buf = Buffer::empty(area);
        cell.render(area, &mut buf); // No panic
    }

    #[test]
    fn test_render_negative_offset_area() {
        // Render with area starting at non-zero coordinates
        let cell = HistoryCell::user_message("hello".to_string());
        let area = Rect::new(10, 5, 80, 3);
        let mut buf = Buffer::empty(Rect::new(0, 0, 100, 20));
        cell.render(area, &mut buf); // No panic
    }

    #[test]
    fn test_render_all_variants_in_sequence_no_panic() {
        let cells = [
            HistoryCell::user_message("hello".to_string()),
            HistoryCell::assistant_message("world".to_string()),
            HistoryCell::tool_call(
                "bash".to_string(),
                serde_json::json!({"cmd": "ls"}),
                Some("ok".to_string()),
                ToolStatus::Completed,
            ),
            HistoryCell::system_message("done".to_string(), SystemMessageStyle::Info),
        ];
        let area = Rect::new(0, 0, 40, 3);
        let mut buf = Buffer::empty(Rect::new(0, 0, 40, 20));
        for cell in &cells {
            cell.render(area, &mut buf);
        }
    }

    // =========================================================================
    // Trait checks: Debug, Clone, PartialEq
    // =========================================================================

    #[test]
    fn test_history_cell_debug() {
        let cell = HistoryCell::user_message("test".to_string());
        let debug_str = format!("{:?}", cell);
        assert!(debug_str.contains("UserMessage") || debug_str.contains("content"));
    }

    #[test]
    fn test_history_cell_clone() {
        let cell = HistoryCell::user_message("hello".to_string());
        let cloned = cell.clone();
        match (&cell, &cloned) {
            (HistoryCell::UserMessage { content: a, .. },
             HistoryCell::UserMessage { content: b, .. }) => {
                assert_eq!(a, b);
            }
            _ => panic!("clone should preserve variant"),
        }
    }

    #[test]
    fn test_tool_status_partial_eq() {
        assert_eq!(ToolStatus::Running, ToolStatus::Running);
        assert_ne!(ToolStatus::Running, ToolStatus::Completed);
        assert_ne!(ToolStatus::Failed, ToolStatus::Pending);
    }

    #[test]
    fn test_system_message_style_partial_eq() {
        assert_eq!(SystemMessageStyle::Info, SystemMessageStyle::Info);
        assert_ne!(SystemMessageStyle::Info, SystemMessageStyle::Warning);
        assert_ne!(SystemMessageStyle::Warning, SystemMessageStyle::Error);
    }

    // =========================================================================
    // Constructor timestamp verification
    // =========================================================================

    #[test]
    fn test_user_message_timestamp_is_recent() {
        let before = chrono::Utc::now();
        let cell = HistoryCell::user_message("test".to_string());
        let after = chrono::Utc::now();
        match cell {
            HistoryCell::UserMessage { timestamp, .. } => {
                assert!(timestamp >= before || timestamp <= after,
                    "timestamp should be set to approximately now");
            }
            _ => panic!("expected UserMessage"),
        }
    }

    #[test]
    fn test_assistant_message_timestamp_is_recent() {
        let before = chrono::Utc::now();
        let cell = HistoryCell::assistant_message("test".to_string());
        let after = chrono::Utc::now();
        match cell {
            HistoryCell::AssistantMessage { timestamp, .. } => {
                assert!(timestamp >= before || timestamp <= after);
            }
            _ => panic!("expected AssistantMessage"),
        }
    }

    #[test]
    fn test_tool_call_no_timestamp() {
        // ToolCall doesn't have a timestamp field — verify the variant is clean
        let cell = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({"cmd": "ls"}),
            None,
            ToolStatus::Running,
        );
        match cell {
            HistoryCell::ToolCall { tool_name, status, .. } => {
                assert_eq!(tool_name, "bash");
                assert_eq!(status, ToolStatus::Running);
            }
            _ => panic!("expected ToolCall"),
        }
    }

    // =========================================================================
    // Renderable trait method consistency
    // =========================================================================

    #[test]
    fn test_renderable_trait_implemented_for_all_variants() {
        // Verify all variants satisfy the Renderable trait bounds
        fn assert_renderable(_: &dyn Renderable) {}

        let user = HistoryCell::user_message("hi".to_string());
        let assistant = HistoryCell::assistant_message("hi".to_string());
        let tool = HistoryCell::tool_call(
            "bash".to_string(),
            serde_json::json!({}),
            None,
            ToolStatus::Running,
        );
        let sys = HistoryCell::system_message("hi".to_string(), SystemMessageStyle::Info);

        assert_renderable(&user);
        assert_renderable(&assistant);
        assert_renderable(&tool);
        assert_renderable(&sys);
    }
}